-- Baseline schema, generated from the JPA entities (Hibernate create, pg_dump --schema-only).
-- Enum CHECK constraints Hibernate adds are left out on purpose: adding an enum value needs no migration.
-- Never edit this file once it has run anywhere; add a V<n>__ file instead.

CREATE TABLE accounts (
    active boolean NOT NULL,
    code integer,
    show_in_alerts boolean NOT NULL,
    threshold_pct numeric(5,2),
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    statement_type character varying(20),
    type character varying(20) NOT NULL,
    icon character varying(40),
    name character varying(120) NOT NULL
);

ALTER TABLE accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE budget_history (
    new_value numeric(14,2) NOT NULL,
    period date NOT NULL,
    previous_value numeric(14,2),
    account_id bigint NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE budget_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME budget_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE budgets (
    amount numeric(14,2) NOT NULL,
    period date NOT NULL,
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    origin character varying(20) NOT NULL
);

ALTER TABLE budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE exchange_rates (
    rate_date date NOT NULL,
    value numeric(10,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    context character varying(20) NOT NULL,
    source character varying(20) NOT NULL
);

ALTER TABLE exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE income_entries (
    bank_fee numeric(14,2) NOT NULL,
    entry_date date NOT NULL,
    net_amount_rd numeric(14,2) NOT NULL,
    original_amount numeric(14,2) NOT NULL,
    currency character varying(5) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    destination_account_id bigint NOT NULL,
    exchange_rate_id bigint,
    id bigint NOT NULL,
    journal_entry_id bigint,
    source character varying(50) NOT NULL
);

ALTER TABLE income_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME income_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE journal_entries (
    amount numeric(14,2) NOT NULL,
    budget_period date NOT NULL,
    entry_date date NOT NULL,
    occurrence_index integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    reference_id bigint,
    reverses_entry_id bigint,
    user_id bigint NOT NULL,
    correction_type character varying(20),
    source character varying(30) NOT NULL,
    description character varying(200) NOT NULL
);

ALTER TABLE journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE journal_lines (
    amount_rd numeric(14,2) NOT NULL,
    original_amount numeric(14,2) NOT NULL,
    currency character varying(5) NOT NULL,
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    exchange_rate_id bigint,
    id bigint NOT NULL,
    journal_entry_id bigint NOT NULL,
    side character varying(10) NOT NULL
);

ALTER TABLE journal_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME journal_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE loan_installments (
    actual_payment_date date,
    number integer NOT NULL,
    scheduled_amount numeric(14,2) NOT NULL,
    scheduled_date date NOT NULL,
    scheduled_interest numeric(14,2),
    scheduled_principal numeric(14,2),
    id bigint NOT NULL,
    journal_entry_id bigint,
    loan_id bigint NOT NULL,
    status character varying(10) NOT NULL
);

ALTER TABLE loan_installments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME loan_installments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE loans (
    active boolean NOT NULL,
    installment_amount numeric(14,2) NOT NULL,
    num_installments integer,
    principal numeric(14,2) NOT NULL,
    rate numeric(6,3) NOT NULL,
    start_date date NOT NULL,
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    frequency character varying(10) NOT NULL,
    type character varying(10) NOT NULL,
    counterparty_name character varying(120) NOT NULL
);

ALTER TABLE loans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME loans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE merchant_dictionary (
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    text_pattern character varying(150) NOT NULL
);

ALTER TABLE merchant_dictionary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME merchant_dictionary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE principal_payments (
    amount numeric(14,2) NOT NULL,
    payment_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    journal_entry_id bigint,
    loan_id bigint NOT NULL,
    user_id bigint NOT NULL,
    effect character varying(20) NOT NULL
);

ALTER TABLE principal_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME principal_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE statement_imports (
    closing_balance numeric(14,2),
    closing_balance_usd numeric(14,2),
    cut_off_date date,
    minimum_payment numeric(14,2),
    minimum_payment_usd numeric(14,2),
    payment_due_date date,
    statement_date date NOT NULL,
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    file_name character varying(200),
    error_message character varying(500)
);

ALTER TABLE statement_imports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME statement_imports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE statement_lines (
    amount numeric(14,2) NOT NULL,
    budget_period date NOT NULL,
    is_excluded boolean NOT NULL,
    line_date date NOT NULL,
    occurrence_index integer NOT NULL,
    currency character varying(5) NOT NULL,
    account_id bigint NOT NULL,
    category_account_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    journal_line_id bigint,
    statement_import_id bigint NOT NULL,
    line_type character varying(20),
    exclusion_reason character varying(40),
    description character varying(200) NOT NULL
);

ALTER TABLE statement_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME statement_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users (
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(150)
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT accounts_user_id_code_key UNIQUE (user_id, code);

ALTER TABLE ONLY budget_history
    ADD CONSTRAINT budget_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY budgets
    ADD CONSTRAINT budgets_account_id_period_key UNIQUE (account_id, period);

ALTER TABLE ONLY budgets
    ADD CONSTRAINT budgets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY exchange_rates
    ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY income_entries
    ADD CONSTRAINT income_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY journal_entries
    ADD CONSTRAINT journal_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY journal_lines
    ADD CONSTRAINT journal_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY loan_installments
    ADD CONSTRAINT loan_installments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY loans
    ADD CONSTRAINT loans_account_id_key UNIQUE (account_id);

ALTER TABLE ONLY loans
    ADD CONSTRAINT loans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY merchant_dictionary
    ADD CONSTRAINT merchant_dictionary_pkey PRIMARY KEY (id);

ALTER TABLE ONLY merchant_dictionary
    ADD CONSTRAINT merchant_dictionary_text_pattern_user_id_key UNIQUE (text_pattern, user_id);

ALTER TABLE ONLY principal_payments
    ADD CONSTRAINT principal_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY statement_imports
    ADD CONSTRAINT statement_imports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT statement_lines_account_id_line_date_description_amount_cur_key UNIQUE (account_id, line_date, description, amount, currency, occurrence_index);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT statement_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY journal_lines
    ADD CONSTRAINT fk1mucajfkxo6i8ldmy61xsaf85 FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id);

ALTER TABLE ONLY budget_history
    ADD CONSTRAINT fk2uokddwpv9f0w43aujn5mimgt FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY budget_history
    ADD CONSTRAINT fk3sbst9dsjlv16pb8rsfutagbr FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT fk44n21m18od0r29vxwii98mrvg FOREIGN KEY (statement_import_id) REFERENCES statement_imports(id);

ALTER TABLE ONLY journal_lines
    ADD CONSTRAINT fk4jn90iw67xup5dmew92gb2chw FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rates(id);

ALTER TABLE ONLY loan_installments
    ADD CONSTRAINT fk6euj5fvxeb4ty0c1a42bt69b FOREIGN KEY (loan_id) REFERENCES loans(id);

ALTER TABLE ONLY loans
    ADD CONSTRAINT fk6xxlcjc0rqtn5nq28vjnx5t9d FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY merchant_dictionary
    ADD CONSTRAINT fk7r08w0ewfbr5ktpb1cceyhdpu FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY budgets
    ADD CONSTRAINT fk8ejw00f6x180r8ks8d1bcu8ok FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY loan_installments
    ADD CONSTRAINT fk9qu2c0xtjxcxqvodpu6l6fy2d FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id);

ALTER TABLE ONLY journal_entries
    ADD CONSTRAINT fkdboe7b8thnf8ef2ao9h0ddxtn FOREIGN KEY (reverses_entry_id) REFERENCES journal_entries(id);

ALTER TABLE ONLY loans
    ADD CONSTRAINT fkeja64hsi0agxgtppa7uccxrh4 FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY income_entries
    ADD CONSTRAINT fkgojt2u7lxqrm0x3cr9pw47l3l FOREIGN KEY (destination_account_id) REFERENCES accounts(id);

ALTER TABLE ONLY principal_payments
    ADD CONSTRAINT fki5gqk2nexwvkvgc4flgay27gy FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id);

ALTER TABLE ONLY statement_imports
    ADD CONSTRAINT fkik21iq2e4nm1982axgrsyst2h FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT fkkmj8d0ncq4567ikbstuf57ncn FOREIGN KEY (category_account_id) REFERENCES accounts(id);

ALTER TABLE ONLY principal_payments
    ADD CONSTRAINT fkn7dwr1n5bi8rt5r4krx6kpnsg FOREIGN KEY (loan_id) REFERENCES loans(id);

ALTER TABLE ONLY principal_payments
    ADD CONSTRAINT fkn8agfj93ehn56nhi1ejkmgcwp FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY income_entries
    ADD CONSTRAINT fkndc0tc0ediw3c1nvannliela9 FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id);

ALTER TABLE ONLY journal_lines
    ADD CONSTRAINT fknimgx551fkl6f1xi07yc816ie FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT fknj1wqquhxnv6d0yq55y3oyt2d FOREIGN KEY (journal_line_id) REFERENCES journal_lines(id);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY journal_entries
    ADD CONSTRAINT fko39gbcpt8kwv3d7qirn4uikua FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY statement_lines
    ADD CONSTRAINT fkpth6lnamcomip07cfp84voq3g FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE ONLY merchant_dictionary
    ADD CONSTRAINT fkpx7kdecwq6wsx74ntbrpr20l1 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY income_entries
    ADD CONSTRAINT fkrcg5177udq0cvoa8xe9vfkxjh FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rates(id);

ALTER TABLE ONLY statement_imports
    ADD CONSTRAINT fkrx235h23lf48rc7a55ae9e2ke FOREIGN KEY (user_id) REFERENCES users(id);
