/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
import { MonthlyBalancePoint } from '../models/monthly-balance-point';
import { TransactionItem } from '../models/transaction-item';
export interface AccountDetailResponse {
  balance?: number;
  code?: string | null;
  id?: number;
  loanAccount?: boolean;
  loanId?: number | null;
  name?: string;
  showInAlerts?: boolean;
  thresholdPct?: number | null;
  totalTransactions?: number;
  transactions?: Array<TransactionItem>;
  trend?: Array<MonthlyBalancePoint>;
  type?: AccountType;
}
