/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
import { LoanType } from '../models/loan-type';
export interface AccountSummaryResponse {

  /**
   * Signed balance in RD$ (positive = normal balance for account type)
   */
  balance?: number;
  code?: string | null;
  id?: number;
  lastTransactionDate?: string | null;
  lastTransactionDescription?: string | null;

  /**
   * RD$ amount of the last journal line for this account
   */
  lastTransactionValue?: number | null;
  loanAccount?: boolean;
  loanCounterpartyName?: string | null;

  /**
   * Present only when loanAccount is true
   */
  loanId?: number | null;
  loanInstallmentAmount?: number | null;
  loanNextInstallmentDate?: string | null;
  loanRemainingBalance?: number | null;
  loanTotalAmount?: number | null;
  loanType?: LoanType;
  name?: string;
  showInAlerts?: boolean;

  /**
   * Budget threshold as a percentage of income (e.g. 20 = 20%)
   */
  thresholdPct?: number | null;
  type?: AccountType;
}
