/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
import { StatementType } from '../models/statement-type';
export interface AccountResponse {
  active?: boolean;
  code?: number | null;
  createdAt?: string;

  /**
   * Tabler icon name (e.g. credit-card)
   */
  icon?: string | null;
  id?: number;

  /**
   * True when this account is managed by a Loan record — shown in the Loans section, not the regular account list
   */
  loanAccount?: boolean;
  name?: string;
  showInAlerts?: boolean;

  /**
   * Set on accounts bank statements are uploaded for
   */
  statementType?: StatementType;
  thresholdPct?: number | null;
  type?: AccountType;
}
