/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
export interface AccountResponse {
  active?: boolean;
  code?: number | null;
  createdAt?: string;
  id?: number;

  /**
   * True when this account is managed by a Loan record — shown in the Loans section, not the regular account list
   */
  loanAccount?: boolean;
  name?: string;
  showInAlerts?: boolean;
  thresholdPct?: number | null;
  type?: AccountType;
}
