/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetUpdateItem } from '../models/budget-update-item';
export interface BatchBudgetUpdateRequest {
  period: string;
  updates: Array<BudgetUpdateItem>;
}
