/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetStatementResult } from '../models/budget-statement-result';
export interface BudgetCardSummary {
  accountId: number;

  /**
   * Sum of the saved budgets of categories with card spend; null when none
   */
  budget?: number | null;
  icon?: string | null;
  name: string;

  /**
   * The month's posted card charges, RD$
   */
  spent: number;

  /**
   * From the month's card lines, payments included; null when the month has none
   */
  statement?: BudgetStatementResult;
}
