/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetLoanPayment } from '../models/budget-loan-payment';
export interface BudgetSavingsSummary {
  accountId: number;

  /**
   * Ledger balance at the end of the month, RD$
   */
  balance: number;
  icon?: string | null;

  /**
   * The month's income-account credits against savings, RD$
   */
  income: number;

  /**
   * Loan installments paid or collected in the month, oldest first
   */
  loanPayments?: Array<BudgetLoanPayment>;
  name: string;
}
