/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetStatementTotals } from '../models/budget-statement-totals';
export interface BudgetCardStatement {
  cutOffDate: string;
  paymentDueDate?: string | null;
  rd: BudgetStatementTotals;

  /**
   * Null when the statement has no US$ movements or balance
   */
  usd?: BudgetStatementTotals;
}
