/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCardStatement } from '../models/budget-card-statement';
export interface BudgetCardSummary {
  accountId: number;

  /**
   * The card's own budget, the latest one saved for this month or an earlier one (it carries forward until changed); null when none was ever saved or the latest is 0
   */
  budget?: number | null;

  /**
   * First day of the month that budget was saved for; equals the period when saved this month, earlier when carried forward
   */
  budgetFromMonth?: string | null;
  icon?: string | null;
  name: string;

  /**
   * Posted charges of the card statement cut in the month, RD$
   */
  spent: number;

  /**
   * The latest card statement up to the month (its billing cycle), as the bank reports it; null without one
   */
  statement?: BudgetCardStatement;

  /**
   * The latest card RD$ per US$ rate; null when none was saved (US$ lines then stay unposted)
   */
  usdRate?: number | null;
}
