/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The card's RD$ balance at the cut-off date, bank vs ledger, and what explains the gap:
 * bank = ledger + pending + paymentsToReconcile + difference. US$ isn't reconciled (a
 * payment from savings is always RD$, even when it pays the US$ balance); only how many
 * of the cycle's US$ charges are posted.
 */
export interface BudgetCardCheck {

  /**
   * bank − ledger − pending − paymentsToReconcile; 0 when the gap is fully explained
   */
  difference: number;

  /**
   * The card's RD$ ledger balance (owed) at the cut-off date
   */
  ledger: number;

  /**
   * RD$ payments from savings to the card in the ledger minus the RD$ payment rows the bank applied,
   * up to the cut-off. Positive: payments the bank hasn't applied yet, or that paid the US$ balance;
   * negative: payments the bank applied whose savings statement isn't uploaded.
   */
  paymentsToReconcile: number;

  /**
   * Net RD$ of the card's unposted, non-excluded lines dated up to the cut-off (charges positive)
   */
  pending: number;
  pendingCount: number;

  /**
   * US$ charges in the billing cycle
   */
  usdCharges: number;

  /**
   * How many of them are posted (they wait for a card rate)
   */
  usdPosted: number;
}
