/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetAccountOption {
  accountId: number;
  icon?: string | null;
  kind: 'EXPENSE' | 'INCOME' | 'LOAN' | 'CARD';
  name: string;
}
