/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategoryOption } from '../models/budget-category-option';
import { StatementType } from '../models/statement-type';
export interface BudgetTransactionLine {

  /**
   * RD$; positive = charge, negative = payment or credit
   */
  amount: number;
  categoryId?: number | null;
  categoryName?: string | null;
  date: string;
  description: string;
  lineId: number;
  source: StatementType;
  sourceIcon?: string | null;
  status: 'POSTED' | 'PENDING';

  /**
   * Two expense categories to offer as chips, never the current one
   */
  suggestions: Array<BudgetCategoryOption>;
}
