/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCardStatement } from '../models/budget-card-statement';
export interface BudgetCardSummary {
  accountId: number;

  /**
   * Sum of the saved budgets of categories with card spend; null when none
   */
  budget?: number | null;
  icon?: string | null;
  name: string;

  /**
   * Posted charges of the card statement cut in the month, RD$
   */
  spent: number;

  /**
   * The latest card statement up to the month (its billing cycle), as the bank reports it; null without one
   */
  statement?: BudgetCardStatement;

  /**
   * The latest card RD$ per US$ rate; null when none was saved (US$ lines then stay unposted)
   */
  usdRate?: number | null;
}
