/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetBankBalance {

  /**
   * The balance the bank reports at that date ("Balance final"), RD$
   */
  bank: number;

  /**
   * The statement's cut-off date
   */
  date: string;

  /**
   * The ledger balance of the account at the same date, RD$; equal to bank when everything is posted
   */
  ledger: number;
}
