/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategoryOption } from '../models/budget-category-option';
import { StatementType } from '../models/statement-type';
export interface BudgetTransactionLine {

  /**
   * RD$; positive = charge, negative = payment or credit
   */
  amount: number;
  categoryId?: number | null;
  categoryName?: string | null;

  /**
   * The currency the bank charged in
   */
  currency: 'RD' | 'USD';
  date: string;
  description: string;
  lineId: number;

  /**
   * The amount in `currency`, signed like amount (e.g. US$4.00 for a US$ charge)
   */
  originalAmount: number;
  source: StatementType;
  sourceIcon?: string | null;
  status: 'POSTED' | 'PENDING';

  /**
   * Two categories to offer as chips, never the current one; income accounts for money in (CREDIT lines), expense accounts otherwise
   */
  suggestions: Array<BudgetCategoryOption>;
}
