/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanType } from '../models/loan-type';
export interface BudgetLoanPayment {

  /**
   * What was paid or collected, RD$ (the bank's amount when it came from a statement)
   */
  amount: number;
  date: string;
  installmentNumber: number;

  /**
   * The interest part of amount, RD$
   */
  interest: number;
  loanAccountId: number;
  loanName: string;
  loanType: LoanType;
  totalInstallments?: number | null;
}
