/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetBankBalance } from '../models/budget-bank-balance';
import { BudgetLoanPayment } from '../models/budget-loan-payment';
export interface BudgetSavingsSummary {
  accountId: number;

  /**
   * Ledger balance at the end of the month, RD$
   */
  balance: number;

  /**
   * The bank's balance from the latest savings statement up to the month; null without one
   */
  bankBalance?: BudgetBankBalance;
  icon?: string | null;

  /**
   * The month's income-account credits against savings, RD$
   */
  income: number;

  /**
   * Loan installments paid or collected in the month, oldest first
   */
  loanPayments?: Array<BudgetLoanPayment>;
  name: string;
}
