/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementType } from '../models/statement-type';
export interface BudgetLastUpload {
  accountId: number;
  kind: StatementType;

  /**
   * The account's latest upload; null if it never had one
   */
  uploadedAt?: string | null;
}
