/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One currency of a card statement, in that currency (never converted)
 */
export interface BudgetStatementTotals {

  /**
   * The balance at the cut-off date, as printed on the statement
   */
  balance?: number | null;

  /**
   * Charges in the billing cycle
   */
  charges: number;

  /**
   * Payments and other credits in the billing cycle
   */
  credits: number;
  minimumPayment?: number | null;

  /**
   * balance − charges + credits; null when the statement has no balance
   */
  previousBalance?: number | null;
}
