/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetLoanPayment } from '../models/budget-loan-payment';
import { BudgetTransactionLine } from '../models/budget-transaction-line';
import { StatementType } from '../models/statement-type';
export interface BudgetCategoryRow {
  accountId: number;

  /**
   * The month's debits − credits on the category (by budget period), corrections included
   */
  actual: number;

  /**
   * The budget in force, the latest one saved for this month or an earlier one (it carries forward until changed); null when none was ever saved or the latest is 0
   */
  budget?: number | null;

  /**
   * First day of the month that budget was saved for; equals the period when saved this month, earlier when carried forward
   */
  budgetFromMonth?: string | null;
  icon?: string | null;

  /**
   * Read-only interest of the month's received-loan installments booked to this category
   */
  loanInterest?: Array<BudgetLoanPayment>;
  name: string;

  /**
   * Statement accounts the spend came from, card first
   */
  origins: Array<StatementType>;
  transactions: Array<BudgetTransactionLine>;
}
