/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetAccountOption } from '../models/budget-account-option';
import { BudgetCardSummary } from '../models/budget-card-summary';
import { BudgetCategoryOption } from '../models/budget-category-option';
import { BudgetCategoryRow } from '../models/budget-category-row';
import { BudgetLastUpload } from '../models/budget-last-upload';
import { BudgetSavingsSummary } from '../models/budget-savings-summary';
import { BudgetTransactionLine } from '../models/budget-transaction-line';
export interface BudgetScreenResponse {

  /**
   * Every account a line can be categorized to, each with its kind: active expense and income accounts, active loans and the card. The UI picks which kinds each line offers.
   */
  accountOptions?: Array<BudgetAccountOption>;

  /**
   * The first active account with statementType CREDIT_CARD; null if there is none
   */
  card?: BudgetCardSummary;
  categories: Array<BudgetCategoryRow>;

  /**
   * Active income accounts, offered in a separate "Ingresos" group when picking a category
   */
  incomeOptions?: Array<BudgetCategoryOption>;
  lastUploads: Array<BudgetLastUpload>;

  /**
   * Active loans, offered in a separate "Préstamos" group when picking a category
   */
  loanOptions?: Array<BudgetCategoryOption>;
  period: string;

  /**
   * The first active account with statementType SAVINGS; null if there is none
   */
  savings?: BudgetSavingsSummary;

  /**
   * Every unposted, non-excluded line of imports that aren't reversed, whatever its month, newest first
   */
  uncategorized: Array<BudgetTransactionLine>;
}
