/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetCardPayment {

  /**
   * RD$ paid to the card
   */
  amount: number;
  date: string;
  lineId: number;
}
