/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementType } from '../models/statement-type';

/**
 * How complete the month is, from its statements
 */
export interface BudgetMonthStatus {

  /**
   * The statement accounts (card, savings) whose statement for the month isn't uploaded: for the card, a statement cut in the month; for savings, rows in the month and a statement whose cut-off is on or after its last day. Reversed and failed statements don't count.
   */
  missingStatements: Array<StatementType>;

  /**
   * The month's lines (by budget period) still unposted and not excluded
   */
  pendingCount: number;
}
