/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetLoanPayment } from '../models/budget-loan-payment';
import { BudgetTransactionLine } from '../models/budget-transaction-line';
import { StatementType } from '../models/statement-type';
export interface BudgetCategoryRow {
  accountId: number;

  /**
   * The month's debits − credits on the category (by budget period), corrections included
   */
  actual: number;

  /**
   * The budget saved for the month
   */
  budget?: number | null;
  icon?: string | null;

  /**
   * Read-only interest of the month's received-loan installments booked to this category
   */
  loanInterest?: Array<BudgetLoanPayment>;
  name: string;

  /**
   * Statement accounts the spend came from, card first
   */
  origins: Array<StatementType>;

  /**
   * The most recent earlier saved budget; only when budget is null (a hint, not a budget)
   */
  previousBudget?: number | null;
  transactions: Array<BudgetTransactionLine>;
}
