/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetReportAccountRow {
  accountId?: number;
  actualAmount?: number;
  actualPct?: number | null;
  budgetOrigin?: ('manual' | 'auto_suggested') | null;
  budgetedAmount?: number | null;
  budgetedPct?: number | null;
  isOverThreshold?: boolean;
  name?: string;
  showInAlerts?: boolean;
  thresholdPct?: number | null;
}
