/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementImportStatus } from '../models/statement-import-status';
export interface ConfirmImportResponse {
  id?: number;
  postedEntries?: number;
  status?: StatementImportStatus;
}
