/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
export interface CreateAccountRequest {
  code?: string | null;
  name: string;
  showInAlerts?: boolean;
  thresholdPct?: number | null;
  type: AccountType;
}
