/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReceivedLoanRequest {

  /**
   * Name of the lender
   */
  counterpartyName: string;

  /**
   * Monthly interest rate as a percentage (e.g. 3 = 3%)
   */
  monthlyRate: number;

  /**
   * Number of monthly installments
   */
  numInstallments: number;

  /**
   * Capital received in RD$
   */
  principal: number;
  startDate: string;
}
