/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReceivedLoanRequest {

  /**
   * Name of the lender
   */
  counterpartyName: string;

  /**
   * Where the money went. Omitted: into the savings account (a cash loan). Otherwise the account
   * the loan paid for, e.g. an expense or asset for a financed purchase (a phone bought in
   * installments), so savings isn't touched. Asset, expense or liability accounts only.
   */
  disbursedToAccountId?: number | null;

  /**
   * Monthly interest rate as a percentage (e.g. 3 = 3%)
   */
  monthlyRate: number;

  /**
   * Number of monthly installments
   */
  numInstallments: number;

  /**
   * Capital received in RD$
   */
  principal: number;
  startDate: string;
}
