/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateIncomeEntryRequest {
  amount: number;

  /**
   * Bank fee deducted in RD$. Defaults to 0.
   */
  bankFee?: number;
  currency: 'RD' | 'USD';
  entryDate: string;

  /**
   * Exchange rate (RD$ per USD). Required when currency is USD.
   */
  rate?: number | null;
  source: 'payroll' | 'other';
}
