/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMerchantMappingRequest {
  accountId: number;

  /**
   * Text pattern as it appears in the statement (stored uppercase)
   */
  pattern: string;
}
