/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
import { StatementType } from '../models/statement-type';
export interface CreateAccountRequest {
  code?: number | null;

  /**
   * Tabler icon name (e.g. credit-card)
   */
  icon?: string | null;
  name: string;
  showInAlerts?: boolean;

  /**
   * Set on accounts bank statements are uploaded for
   */
  statementType?: StatementType;
  thresholdPct?: number | null;
  type: AccountType;
}
