/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGivenLoanRequest {

  /**
   * Name of the borrower
   */
  counterpartyName: string;

  /**
   * Desired weekly installment amount in RD$
   */
  installmentAmount: number;

  /**
   * Capital lent in RD$
   */
  principal: number;

  /**
   * Total flat rate as a percentage (e.g. 15 = 15%)
   */
  rate: number;
  startDate: string;
}
