/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLoanRequest {

  /**
   * Requested loan amount in USD
   */
  amount: number;

  /**
   * Loan term in months
   */
  term: number;
}
