/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeEntryResponse {
  bankFee?: number;
  currency?: string;
  entryDate?: string;
  id?: number;
  netAmountRd?: number;
  originalAmount?: number;
  rate?: number | null;
  source?: string;
}
