/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanFrequency } from '../models/loan-frequency';
import { LoanType } from '../models/loan-type';
export interface LoanResponse {
  accountCode?: string | null;
  accountName?: string;
  active?: boolean;
  counterpartyName?: string;
  frequency?: LoanFrequency;
  id?: number;
  installmentAmount?: number;
  nextInstallmentDate?: string | null;
  paidInstallments?: number;
  principal?: number;
  remainingBalance?: number;
  totalAmount?: number;
  totalInstallments?: number | null;
  type?: LoanType;
}
