/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanType } from './loan-type';

/**
 * Each possible value of `LoanType`
 */
export const LOAN_TYPE: LoanType[] = [
  'GIVEN',
  'RECEIVED'
];