/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanInstallmentDto } from '../models/loan-installment-dto';
import { LoanResponse } from '../models/loan-response';
export type LoanDetailResponse = LoanResponse & {
'installments'?: Array<LoanInstallmentDto>;
};

