/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanFrequency } from '../models/loan-frequency';
import { LoanType } from '../models/loan-type';
export interface LoanData {
  counterpartyName?: string;
  frequency?: LoanFrequency;
  installmentAmount?: number;
  numInstallments?: number | null;

  /**
   * Number of PAID installments
   */
  paidCount?: number;
  principal?: number;
  rate?: number;

  /**
   * Remaining loan balance (principal not yet paid)
   */
  remainingBalance?: number;
  startDate?: string;
  type?: LoanType;
}
