/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanFrequency } from './loan-frequency';

/**
 * Each possible value of `LoanFrequency`
 */
export const LOAN_FREQUENCY: LoanFrequency[] = [
  'WEEKLY',
  'MONTHLY'
];