/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoanInstallmentDto {
  number?: number;
  scheduledAmount?: number;
  scheduledDate?: string;
  scheduledInterest?: number | null;
  scheduledPrincipal?: number | null;
  status?: 'PENDING' | 'PAID' | 'OVERDUE';
}
