/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MerchantMappingResponse {
  accountId?: number;
  accountName?: string;
  id?: number;
  pattern?: string;
}
