/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlyBalancePoint {
  balance?: number;

  /**
   * Spanish 3-letter month abbreviation (e.g. "ene", "sep")
   */
  month?: string;
}
