/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PrincipalPaymentRequest {

  /**
   * Principal payment amount in RD$
   */
  amount: number;
  date: string;
  mode: 'REDUCE_TERM' | 'REDUCE_INSTALLMENT';
}
