/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveExchangeRateRequest {

  /**
   * Today when omitted
   */
  rateDate?: string | null;

  /**
   * RD$ per US$, e.g. 60.50
   */
  value: number;
}
