/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveExchangeRateResponse {

  /**
   * US$ lines posted now that a rate exists
   */
  postedLines: number;
  rateDate: string;
  value: number;
}
