/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementType } from './statement-type';

/**
 * Each possible value of `StatementType`
 */
export const STATEMENT_TYPE: StatementType[] = [
  'CREDIT_CARD',
  'SAVINGS'
];