/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementImportStatus } from '../models/statement-import-status';
import { StatementLineDto } from '../models/statement-line-dto';
export interface StatementImportResponse {
  errorMessage?: string | null;
  id?: number;
  lines?: Array<StatementLineDto>;
  status?: StatementImportStatus;
}
