/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementImportStatus } from '../models/statement-import-status';
import { StatementType } from '../models/statement-type';
export interface StatementImportSummaryResponse {
  accountId?: number;
  accountName?: string;
  id?: number;
  lineCount?: number;
  statementDate?: string;
  status?: StatementImportStatus;
  type?: StatementType;
  unresolvedCount?: number;
}
