/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatementImportStatus } from './statement-import-status';

/**
 * Each possible value of `StatementImportStatus`
 */
export const STATEMENT_IMPORT_STATUS: StatementImportStatus[] = [
  'UPLOADED',
  'PROCESSING',
  'PENDING_REVIEW',
  'CONFIRMED',
  'FAILED',
  'REVERSED'
];