/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatementLineDto {
  amount?: number;
  categoryAccountId?: number | null;
  categoryAccountName?: string | null;
  currency?: 'RD' | 'USD';
  description?: string;

  /**
   * Why the line is excluded; null when it isn't
   */
  exclusionReason?: ('CARD_PAYMENT_AVOID_DOUBLE_ENTRY' | 'INITIAL_BALANCE' | 'USER_EXCLUDED' | 'LOAN_PAYMENT_ALREADY_RECORDED') | null;
  id?: number;
  isExcluded?: boolean;

  /**
   * Auto-excluded payment row (e.g. PAGO DEBITO A CUENTA)
   */
  isPayment?: boolean;
  lineDate?: string;
  lineType?: ('DEBIT' | 'CREDIT' | 'INITIAL_BALANCE') | null;

  /**
   * True once the line has produced a journal entry
   */
  posted?: boolean;
}
