/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatementLineDto {
  amount?: number;
  categoryAccountId?: number | null;
  categoryAccountName?: string | null;
  currency?: 'RD' | 'USD';
  description?: string;
  id?: number;
  isExcluded?: boolean;

  /**
   * Auto-excluded payment row (e.g. PAGO DEBITO A CUENTA)
   */
  isPayment?: boolean;
  lineDate?: string;
}
