/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionItem } from '../models/transaction-item';
export interface TransactionPageResponse {
  items?: Array<TransactionItem>;
  totalCount?: number;
}
