/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionItem {
  amountRd?: number;
  date?: string;
  description?: string;
  id?: number;

  /**
   * True when this transaction is beneficial to the user's wealth
   */
  inflow?: boolean;
}
