/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaveExchangeRateRequest } from '../../models/save-exchange-rate-request';
import { SaveExchangeRateResponse } from '../../models/save-exchange-rate-response';

export interface SaveExchangeRate$Params {
      body: SaveExchangeRateRequest
}

export function saveExchangeRate(http: HttpClient, rootUrl: string, params: SaveExchangeRate$Params, context?: HttpContext): Observable<StrictHttpResponse<SaveExchangeRateResponse>> {
  const rb = new RequestBuilder(rootUrl, saveExchangeRate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SaveExchangeRateResponse>;
    })
  );
}

saveExchangeRate.PATH = '/api/v1/exchange-rates';
