/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMerchantMappingRequest } from '../../models/create-merchant-mapping-request';
import { MerchantMappingResponse } from '../../models/merchant-mapping-response';

export interface CreateMerchantMapping$Params {
      body: CreateMerchantMappingRequest
}

export function createMerchantMapping(http: HttpClient, rootUrl: string, params: CreateMerchantMapping$Params, context?: HttpContext): Observable<StrictHttpResponse<MerchantMappingResponse>> {
  const rb = new RequestBuilder(rootUrl, createMerchantMapping.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MerchantMappingResponse>;
    })
  );
}

createMerchantMapping.PATH = '/api/v1/dictionary';
