/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MerchantMappingResponse } from '../../models/merchant-mapping-response';

export interface ListMerchantMappings$Params {
}

export function listMerchantMappings(http: HttpClient, rootUrl: string, params?: ListMerchantMappings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MerchantMappingResponse>>> {
  const rb = new RequestBuilder(rootUrl, listMerchantMappings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MerchantMappingResponse>>;
    })
  );
}

listMerchantMappings.PATH = '/api/v1/dictionary';
