/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MerchantMappingResponse } from '../../models/merchant-mapping-response';
import { UpdateMerchantMappingRequest } from '../../models/update-merchant-mapping-request';

export interface UpdateMerchantMapping$Params {
  id: number;
      body: UpdateMerchantMappingRequest
}

export function updateMerchantMapping(http: HttpClient, rootUrl: string, params: UpdateMerchantMapping$Params, context?: HttpContext): Observable<StrictHttpResponse<MerchantMappingResponse>> {
  const rb = new RequestBuilder(rootUrl, updateMerchantMapping.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MerchantMappingResponse>;
    })
  );
}

updateMerchantMapping.PATH = '/api/v1/dictionary/{id}';
