/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateIncomeEntryRequest } from '../../models/create-income-entry-request';
import { IncomeEntryResponse } from '../../models/income-entry-response';

export interface CreateIncomeEntry$Params {
      body: CreateIncomeEntryRequest
}

export function createIncomeEntry(http: HttpClient, rootUrl: string, params: CreateIncomeEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, createIncomeEntry.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncomeEntryResponse>;
    })
  );
}

createIncomeEntry.PATH = '/api/v1/income-entries';
