/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeEntryResponse } from '../../models/income-entry-response';

export interface ListIncomeEntries$Params {
}

export function listIncomeEntries(http: HttpClient, rootUrl: string, params?: ListIncomeEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeEntryResponse>>> {
  const rb = new RequestBuilder(rootUrl, listIncomeEntries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IncomeEntryResponse>>;
    })
  );
}

listIncomeEntries.PATH = '/api/v1/income-entries';
