/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoanDetailResponse } from '../../models/loan-detail-response';
import { PrincipalPaymentRequest } from '../../models/principal-payment-request';

export interface ApplyPrincipalPayment$Params {
  accountId: number;
      body: PrincipalPaymentRequest
}

export function applyPrincipalPayment(http: HttpClient, rootUrl: string, params: ApplyPrincipalPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, applyPrincipalPayment.PATH, 'post');
  if (params) {
    rb.path('accountId', params.accountId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoanDetailResponse>;
    })
  );
}

applyPrincipalPayment.PATH = '/api/v1/loans/account/{accountId}/principal-payment';
