/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoanDetailResponse } from '../../models/loan-detail-response';

export interface CollectInstallment$Params {
  accountId: number;
  num: number;
}

export function collectInstallment(http: HttpClient, rootUrl: string, params: CollectInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, collectInstallment.PATH, 'post');
  if (params) {
    rb.path('accountId', params.accountId, {});
    rb.path('num', params.num, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoanDetailResponse>;
    })
  );
}

collectInstallment.PATH = '/api/v1/loans/account/{accountId}/installments/{num}/collect';
