/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateGivenLoanRequest } from '../../models/create-given-loan-request';
import { LoanResponse } from '../../models/loan-response';

export interface CreateGivenLoan$Params {
      body: CreateGivenLoanRequest
}

export function createGivenLoan(http: HttpClient, rootUrl: string, params: CreateGivenLoan$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanResponse>> {
  const rb = new RequestBuilder(rootUrl, createGivenLoan.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoanResponse>;
    })
  );
}

createGivenLoan.PATH = '/api/v1/loans';
