/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateReceivedLoanRequest } from '../../models/create-received-loan-request';
import { LoanResponse } from '../../models/loan-response';

export interface CreateReceivedLoan$Params {
      body: CreateReceivedLoanRequest
}

export function createReceivedLoan(http: HttpClient, rootUrl: string, params: CreateReceivedLoan$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanResponse>> {
  const rb = new RequestBuilder(rootUrl, createReceivedLoan.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoanResponse>;
    })
  );
}

createReceivedLoan.PATH = '/api/v1/loans/received';
