/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoanDetailResponse } from '../../models/loan-detail-response';

export interface GetLoan$Params {
  id: number;
}

export function getLoan(http: HttpClient, rootUrl: string, params: GetLoan$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getLoan.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoanDetailResponse>;
    })
  );
}

getLoan.PATH = '/api/v1/loans/{id}';
