/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoanResponse } from '../../models/loan-response';
import { LoanType } from '../../models/loan-type';

export interface GetLoans$Params {
  type?: LoanType;
}

export function getLoans(http: HttpClient, rootUrl: string, params?: GetLoans$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LoanResponse>>> {
  const rb = new RequestBuilder(rootUrl, getLoans.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LoanResponse>>;
    })
  );
}

getLoans.PATH = '/api/v1/loans';
