/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetScreenResponse } from '../../models/budget-screen-response';

export interface GetBudgetScreen$Params {

/**
 * First day of the month (YYYY-MM-01); any day of the month is accepted
 */
  period: string;
}

export function getBudgetScreen(http: HttpClient, rootUrl: string, params: GetBudgetScreen$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetScreenResponse>> {
  const rb = new RequestBuilder(rootUrl, getBudgetScreen.PATH, 'get');
  if (params) {
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetScreenResponse>;
    })
  );
}

getBudgetScreen.PATH = '/api/v1/budget-screen';
