/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionPageResponse } from '../../models/transaction-page-response';

export interface GetAccountTransactions$Params {
  id: number;
  page?: number;
  size?: number;
}

export function getAccountTransactions(http: HttpClient, rootUrl: string, params: GetAccountTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionPageResponse>> {
  const rb = new RequestBuilder(rootUrl, getAccountTransactions.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransactionPageResponse>;
    })
  );
}

getAccountTransactions.PATH = '/api/v1/accounts/{id}/transactions';
