/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountSummaryResponse } from '../../models/account-summary-response';

export interface GetAccountsSummary$Params {
}

export function getAccountsSummary(http: HttpClient, rootUrl: string, params?: GetAccountsSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountSummaryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAccountsSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AccountSummaryResponse>>;
    })
  );
}

getAccountsSummary.PATH = '/api/v1/accounts/summary';
