/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmImportResponse } from '../../models/confirm-import-response';

export interface ConfirmStatementImport$Params {
  id: number;
}

export function confirmStatementImport(http: HttpClient, rootUrl: string, params: ConfirmStatementImport$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfirmImportResponse>> {
  const rb = new RequestBuilder(rootUrl, confirmStatementImport.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfirmImportResponse>;
    })
  );
}

confirmStatementImport.PATH = '/api/v1/statement-imports/{id}/confirm';
