/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatementImportResponse } from '../../models/statement-import-response';

export interface GetStatementImport$Params {
  id: number;
}

export function getStatementImport(http: HttpClient, rootUrl: string, params: GetStatementImport$Params, context?: HttpContext): Observable<StrictHttpResponse<StatementImportResponse>> {
  const rb = new RequestBuilder(rootUrl, getStatementImport.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatementImportResponse>;
    })
  );
}

getStatementImport.PATH = '/api/v1/statement-imports/{id}';
