/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatementImportSummaryResponse } from '../../models/statement-import-summary-response';

export interface ListStatementImports$Params {
}

export function listStatementImports(http: HttpClient, rootUrl: string, params?: ListStatementImports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatementImportSummaryResponse>>> {
  const rb = new RequestBuilder(rootUrl, listStatementImports.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatementImportSummaryResponse>>;
    })
  );
}

listStatementImports.PATH = '/api/v1/statement-imports';
