/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchStatementLineRequest } from '../../models/patch-statement-line-request';
import { StatementLineDto } from '../../models/statement-line-dto';

export interface PatchStatementLine$Params {
  id: number;
      body: PatchStatementLineRequest
}

export function patchStatementLine(http: HttpClient, rootUrl: string, params: PatchStatementLine$Params, context?: HttpContext): Observable<StrictHttpResponse<StatementLineDto>> {
  const rb = new RequestBuilder(rootUrl, patchStatementLine.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatementLineDto>;
    })
  );
}

patchStatementLine.PATH = '/api/v1/statement-lines/{id}';
