/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatementImportResponse } from '../../models/statement-import-response';
import { StatementType } from '../../models/statement-type';

export interface UploadStatement$Params {
      body: {
'file': Blob;
'accountId': number;
'type': StatementType;
'statementDate': string;
}
}

export function uploadStatement(http: HttpClient, rootUrl: string, params: UploadStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<StatementImportResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadStatement.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatementImportResponse>;
    })
  );
}

uploadStatement.PATH = '/api/v1/statement-imports';
