/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BatchBudgetUpdateRequest } from '../../models/batch-budget-update-request';
import { BudgetReportResponse } from '../../models/budget-report-response';

export interface BatchUpdateBudgets$Params {
      body: BatchBudgetUpdateRequest
}

export function batchUpdateBudgets(http: HttpClient, rootUrl: string, params: BatchUpdateBudgets$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetReportResponse>> {
  const rb = new RequestBuilder(rootUrl, batchUpdateBudgets.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetReportResponse>;
    })
  );
}

batchUpdateBudgets.PATH = '/api/v1/budgets/batch-update';
