/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetReportResponse } from '../../models/budget-report-response';

export interface GetBudgetReport$Params {

/**
 * First day of the report month (e.g. 2026-10-01)
 */
  period: string;
}

export function getBudgetReport(http: HttpClient, rootUrl: string, params: GetBudgetReport$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetReportResponse>> {
  const rb = new RequestBuilder(rootUrl, getBudgetReport.PATH, 'get');
  if (params) {
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetReportResponse>;
    })
  );
}

getBudgetReport.PATH = '/api/v1/reports/budget';
